export const CONNEXION_ON = 'CONNEXION_ON';
export const SET_USER_FIRSTNAME = 'SET_USER_FIRSTNAME';
export const SET_USER_LASTNAME = 'SET_USER_LASTNAME';
export const SET_USER_ISCONNECT = 'SET_USER_ISCONNECT';
export const SET_USER_EMAIL = 'SET_USER_AGE';